#!/bin/sh

TAG="huawei-sn6140-audio-sleep"

case "$1" in
  pre)
    logger -t "$TAG" "pre $2"
    ;;
  post)
    logger -t "$TAG" "post $2; queueing resume repair"
    if ! systemctl restart --no-block huawei-sn6140-audio-resume-fix.service; then
      logger -p user.err -t "$TAG" "failed to queue resume repair"
      exit 1
    fi
    ;;
esac
